### ISSUE TITLE
已经star，代码很专业；运行中有点问题无法登录manager系统

### ISSUE THREAD

**Issue by arraycto** [mikuhuyo/wanxin-p2p#3]
岳大佬，无法登录manager系统，极有可能是数据初始化的问题，麻烦提供一些初始化的数据（目前只有sql，少很多测试数据）
![image](https://user-images.githubusercontent.com/37463247/106701589-de08ba80-6621-11eb-9d46-e95b08abaa6d.png)

报错信息
```
`2021-02-03 13:12:03.631  INFO 16288 --- [lientSelector_1] RocketmqRemoting                         : closeChannel: close the connection to remote address[] result: true
 Time：4 ms - ID：com.wanxin.consumer.mapper.ConsumerMapper.selectOne
Execute SQL：SELECT ID,USERNAME,FULLNAME,ID_NUMBER,USER_NO,MOBILE,USER_TYPE,ROLE,AUTH_LIST,IS_BIND_CARD,STATUS,LOAN_AMOUNT,REQUEST_NO FROM consumer WHERE MOBILE = '13990900909'

2021-02-03 13:12:17.452 ERROR 16288 --- [io-53050-exec-8] c.w.c.c.GlobalExceptionHandler           : [系统异常]-null
2021-02-03 13:12:18.641  INFO 16288 --- [lientSelector_1] RocketmqRemoting                         : closeChannel: close the connection to remote address[] result: true
`
```

**Comment by mikuhuyo** [comment]
存管开通问题已修复, 至于这个wanxin-p2p-manager部分后台接口问题还未修复, ~我太菜了~不要急哦(o(╥﹏╥)o).

**Comment by mikuhuyo** [comment]
测试数据就用自己开户生成的吧(╮(╯▽╰)╭).

**Comment by arraycto** [comment]
您的开户指的是？不能登录无法开户吧，也尝试中

**Comment by mikuhuyo** [comment]
老哥后台前端登录问题已修复, 但是还没上传到github.
骚等, 等我完成我的模块就将代码推送到github.

**Comment by kaiwenli** [comment]
麻烦您尽快删除一下https://github.com/arraycto/kwc_wpm  这个版本仓库吧。谢谢！！！


我的电话是：189 1130 0582

**Comment by arraycto** [comment]
> 麻烦您尽快删除一下https://github.com/arraycto/kwc_wpm 这个版本仓库吧。谢谢！！！
> 
> 我的电话是：189 1130 0582
-------------------------
之前顺手fork别人的代码，现在已经删除，抱歉给您带来不便。
